# HALLMARKS GENE SETS

inflammatory = c(
  "HALLMARK_INFLAMMATORY_RESPONSE",
  "HALLMARK_ALLOGRAFT_REJECTION",
  "HALLMARK_TNFA_SIGNALING_VIA_NFKB",
  "HALLMARK_INTERFERON_ALPHA_RESPONSE",
  "HALLMARK_INTERFERON_GAMMA_RESPONSE",
  "HALLMARK_IL6_JAK_STAT3_SIGNALING",
  "HALLMARK_IL2_STAT5_SIGNALING",
  "HALLMARK_COMPLEMENT",
  "HALLMARK_COAGULATION"
)

damage_res = c(
  "HALLMARK_P53_PATHWAY",
  "HALLMARK_APOPTOSIS",
  "HALLMARK_REACTIVE_OXYGEN_SPECIES_PATHWAY",
  "HALLMARK_DNA_REPAIR",
  "HALLMARK_UV_RESPONSE_UP",
  "HALLMARK_UV_RESPONSE_DN"
)

cell_proliferation = c(
  "HALLMARK_MITOTIC_SPINDLE",
  "HALLMARK_E2F_TARGETS",
  "HALLMARK_G2M_CHECKPOINT",
  "HALLMARK_MYC_TARGETS_V1",
  "HALLMARK_MYC_TARGETS_V2"
)

cell_metabolism = c(
  "HALLMARK_GLYCOLYSIS",
  "HALLMARK_OXIDATIVE_PHOSPHORYLATION",
  "HALLMARK_HYPOXIA",
  "HALLMARK_PEROXISOME",
  "HALLMARK_FATTY_ACID_METABOLISM",
  "HALLMARK_CHOLESTEROL_HOMEOSTASIS",
  "HALLMARK_XENOBIOTIC_METABOLISM",
  "HALLMARK_BILE_ACID_METABOLISM",
  "HALLMARK_HEME_METABOLISM"
)

cell_junction = c(
    "HALLMARK_APICAL_JUNCTION",
    "HALLMARK_APICAL_SURFACE",
    "HALLMARK_EPITHELIAL_MESENCHYMAL_TRANSITION"
  )

differentiation = c(
  "HALLMARK_ANGIOGENESIS",
  "HALLMARK_ADIPOGENESIS",
  "HALLMARK_MYOGENESIS",
  "HALLMARK_SPERMATOGENESIS",
  "HALLMARK_PANCREAS_BETA_CELLS"
)

signaling = c(
  "HALLMARK_ANDROGEN_RESPONSE",
  "HALLMARK_ESTROGEN_RESPONSE_EARLY",
  "HALLMARK_ESTROGEN_RESPONSE_LATE",
  "HALLMARK_NOTCH_SIGNALING",
  "HALLMARK_WNT_BETA_CATENIN_SIGNALING",
  "HALLMARK_TGF_BETA_SIGNALING",
  "HALLMARK_HEDGEHOG_SIGNALING",
  "HALLMARK_MTORC1_SIGNALING",
  "HALLMARK_PI3K_AKT_MTOR_SIGNALING",
  "HALLMARK_KRAS_SIGNALING_UP",
  "HALLMARK_KRAS_SIGNALING_DN",
  "HALLMARK_UNFOLDED_PROTEIN_RESPONSE",
  "HALLMARK_PROTEIN_SECRETION"
)

group = setNames(list(inflammatory, damage_res, cell_proliferation, cell_metabolism,
             cell_junction, differentiation, signaling),
             c("inflammatory", "damage_res", "cell_proliferation", "cell_metabolism",
               "cell_junction", "differentiation", "signaling"))
