# KEGG CELLULAR PROCESS

kegg.cp_cellgrwothanddeath = c(
  "KEGG_CELL_CYCLE",
  "KEGG_OOCYTE_MEIOSIS",
  "KEGG_APOPTOSIS",
  "KEGG_P53_SIGNALING_PATHWAY"
)

kegg.gip_dnarepair = 
  c(
    # Nucleotide metabolism
    "KEGG_DNA_REPLICATION",
    "KEGG_BASE_EXCISION_REPAIR",
    "KEGG_NUCLEOTIDE_EXCISION_REPAIR",
    "KEGG_MISMATCH_REPAIR",
    "KEGG_HOMOLOGOUS_RECOMBINATION",
    "KEGG_NON_HOMOLOGOUS_END_JOINING"
  )

kegg.cp_cellularcommunityandmotility = 
  c(
    # Amino acid metabolism
    "KEGG_FOCAL_ADHESION",
    "KEGG_ADHERENS_JUNCTION",
    "KEGG_TIGHT_JUNCTION",
    "KEGG_GAP_JUNCTION",
    "KEGG_REGULATION_OF_ACTIN_CYTOSKELETON",
    "KEGG_NEUROACTIVE_LIGAND_RECEPTOR_INTERACTION",
    "KEGG_CYTOKINE_CYTOKINE_RECEPTOR_INTERACTION",
    "KEGG_ECM_RECEPTOR_INTERACTION",
    "KEGG_CELL_ADHESION_MOLECULES_CAMS"
  )

kegg.eip_signaltransduction = 
  c(
    # Nucleotide metabolism
    "KEGG_MAPK_SIGNALING_PATHWAY",
    "KEGG_ERBB_SIGNALING_PATHWAY",
    "KEGG_WNT_SIGNALING_PATHWAY",
    "KEGG_NOTCH_SIGNALING_PATHWAY",
    "KEGG_HEDGEHOG_SIGNALING_PATHWAY",
    "KEGG_TGF_BETA_SIGNALING_PATHWAY",
    "KEGG_VEGF_SIGNALING_PATHWAY",
    "KEGG_JAK_STAT_SIGNALING_PATHWAY",
    "KEGG_CALCIUM_SIGNALING_PATHWAY",
    "KEGG_PHOSPHATIDYLINOSITOL_SIGNALING_SYSTEM",
    "KEGG_SPHINGOLIPID_METABOLISM",
    "KEGG_MTOR_SIGNALING_PATHWAY",
    "KEGG_INSULIN_SIGNALING_PATHWAY",
    "KEGG_ADIPOCYTOKINE_SIGNALING_PATHWAY",
    "KEGG_PPAR_SIGNALING_PATHWAY",
    "KEGG_GNRH_SIGNALING_PATHWAY",
    "KEGG_NEUROTROPHIN_SIGNALING_PATHWAY",
    "KEGG_PROGESTERONE_MEDIATED_OOCYTE_MATURATION",
    "KEGG_MELANOGENESIS",
    "KEGG_RENIN_ANGIOTENSIN_SYSTEM"
  )

group = list()
group$kegg.cp_cellgrwothanddeath = kegg.cp_cellgrwothanddeath
group$kegg.gip_dnarepair = kegg.gip_dnarepair
group$kegg.cp_cellularcommunityandmotility = kegg.cp_cellularcommunityandmotility
group$kegg.eip_signaltransduction = kegg.eip_signaltransduction
