kegg.orgsys.immune = c(
  "KEGG_HEMATOPOIETIC_CELL_LINEAGE",
  "KEGG_COMPLEMENT_AND_COAGULATION_CASCADES",
  "KEGG_TOLL_LIKE_RECEPTOR_SIGNALING_PATHWAY",
  "KEGG_NOD_LIKE_RECEPTOR_SIGNALING_PATHWAY",
  "KEGG_RIG_I_LIKE_RECEPTOR_SIGNALING_PATHWAY",
  "KEGG_CYTOSOLIC_DNA_SENSING_PATHWAY",
  "KEGG_NATURAL_KILLER_CELL_MEDIATED_CYTOTOXICITY",
  "KEGG_ANTIGEN_PROCESSING_AND_PRESENTATION",
  "KEGG_T_CELL_RECEPTOR_SIGNALING_PATHWAY",
  "KEGG_B_CELL_RECEPTOR_SIGNALING_PATHWAY",
  "KEGG_FC_EPSILON_RI_SIGNALING_PATHWAY",
  "KEGG_FC_GAMMA_R_MEDIATED_PHAGOCYTOSIS",
  "KEGG_LEUKOCYTE_TRANSENDOTHELIAL_MIGRATION",
  "KEGG_INTESTINAL_IMMUNE_NETWORK_FOR_IGA_PRODUCTION",
  "KEGG_CHEMOKINE_SIGNALING_PATHWAY"
)


kegg.orgsys.circulatory = c(
  "KEGG_CARDIAC_MUSCLE_CONTRACTION",
  "KEGG_VASCULAR_SMOOTH_MUSCLE_CONTRACTION"
)
kegg.orgsys.excretory = c(
  "KEGG_VASOPRESSIN_REGULATED_WATER_REABSORPTION",
  "KEGG_ALDOSTERONE_REGULATED_SODIUM_REABSORPTION",
  "KEGG_PROXIMAL_TUBULE_BICARBONATE_RECLAMATION"
)
kegg.orgsys.nervous = c(
  "KEGG_LONG_TERM_POTENTIATION",
  "KEGG_LONG_TERM_DEPRESSION",
  "KEGG_DORSO_VENTRAL_AXIS_FORMATION",
  "KEGG_AXON_GUIDANCE"
)   
kegg.orgsys.aging = c(
  "KEGG_CIRCADIAN_RHYTHM_MAMMAL"
)

group = list()
group$kegg.orgsys.immune = kegg.orgsys.immune
group$kegg.orgsys.circulatory = kegg.orgsys.circulatory
group$kegg.orgsys.excretory = kegg.orgsys.excretory
group$kegg.orgsys.nervous = kegg.orgsys.nervous
group$kegg.orgsys.aging = kegg.orgsys.aging
