kegg.metab_carbohydrate = 
  c(
    # Carbohydrate metabolism
    "KEGG_GLYCOLYSIS_GLUCONEOGENESIS",
    "KEGG_CITRATE_CYCLE_TCA_CYCLE",
    "KEGG_PENTOSE_PHOSPHATE_PATHWAY",
    "KEGG_PENTOSE_AND_GLUCURONATE_INTERCONVERSIONS",
    "KEGG_FRUCTOSE_AND_MANNOSE_METABOLISM",
    "KEGG_GALACTOSE_METABOLISM",
    "KEGG_ASCORBATE_AND_ALDARATE_METABOLISM",
    "KEGG_STARCH_AND_SUCROSE_METABOLISM",
    "KEGG_AMINO_SUGAR_AND_NUCLEOTIDE_SUGAR_METABOLISM",
    "KEGG_PYRUVATE_METABOLISM",
    "KEGG_GLYOXYLATE_AND_DICARBOXYLATE_METABOLISM",
    "KEGG_PROPANOATE_METABOLISM",
    "KEGG_BUTANOATE_METABOLISM",
    "KEGG_INOSITOL_PHOSPHATE_METABOLISM"
  )
kegg.metab_energy = 
  c(      
    # Energy metabolism
    "KEGG_OXIDATIVE_PHOSPHORYLATION",
    "KEGG_NITROGEN_METABOLISM",
    "KEGG_SULFUR_METABOLISM"
  )
kegg.metab_lipid = 
  c(      
    # Lipid metabolism
    "KEGG_FATTY_ACID_METABOLISM",
    "KEGG_STEROID_BIOSYNTHESIS",
    "KEGG_PRIMARY_BILE_ACID_BIOSYNTHESIS",
    "KEGG_STEROID_HORMONE_BIOSYNTHESIS",
    "KEGG_GLYCEROLIPID_METABOLISM",
    "KEGG_GLYCEROPHOSPHOLIPID_METABOLISM",
    "KEGG_ETHER_LIPID_METABOLISM",
    "KEGG_SPHINGOLIPID_METABOLISM",
    "KEGG_ARACHIDONIC_ACID_METABOLISM",
    "KEGG_LINOLEIC_ACID_METABOLISM",
    "KEGG_ALPHA_LINOLENIC_ACID_METABOLISM",
    "KEGG_BIOSYNTHESIS_OF_UNSATURATED_FATTY_ACIDS"
  )
kegg.metab_nucleotide = 
  c(
    # Nucleotide metabolism
    "KEGG_PURINE_METABOLISM",
    "KEGG_PYRIMIDINE_METABOLISM"
  )
kegg.metab_aminoacid = 
  c(
    # Amino acid metabolism
    "KEGG_ALANINE_ASPARTATE_AND_GLUTAMATE_METABOLISM",
    "KEGG_GLYCINE_SERINE_AND_THREONINE_METABOLISM",
    "KEGG_CYSTEINE_AND_METHIONINE_METABOLISM",
    "KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_DEGRADATION",
    "KEGG_VALINE_LEUCINE_AND_ISOLEUCINE_BIOSYNTHESIS",
    "KEGG_LYSINE_DEGRADATION",
    "KEGG_ARGININE_AND_PROLINE_METABOLISM",
    "KEGG_HISTIDINE_METABOLISM",
    "KEGG_TYROSINE_METABOLISM",
    "KEGG_TRYPTOPHAN_METABOLISM",
    "KEGG_PHENYLALANINE_METABOLISM",
    "KEGG_BETA_ALANINE_METABOLISM",
    "KEGG_TAURINE_AND_HYPOTAURINE_METABOLISM",
    "KEGG_SELENOAMINO_ACID_METABOLISM",
    "KEGG_GLUTATHIONE_METABOLISM"
  )
kegg.metab_glycan = c( 
  # Glycan biosynthesis and metabolism
  "KEGG_N_GLYCAN_BIOSYNTHESIS",
  "KEGG_GLYCOSAMINOGLYCAN_BIOSYNTHESIS_HEPARAN_SULFATE",
  "KEGG_GLYCOSAMINOGLYCAN_BIOSYNTHESIS_CHONDROITIN_SULFATE",
  "KEGG_GLYCOSAMINOGLYCAN_BIOSYNTHESIS_KERATAN_SULFATE",
  "KEGG_GLYCOSYLPHOSPHATIDYLINOSITOL_GPI_ANCHOR_BIOSYNTHESIS",
  "KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_GANGLIO_SERIES",
  "KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_GLOBO_SERIES",
  "KEGG_GLYCOSPHINGOLIPID_BIOSYNTHESIS_LACTO_AND_NEOLACTO_SERIES",
  "KEGG_OTHER_GLYCAN_DEGRADATION"
)
kegg.metab_cofactor = c( 
  # Cofactors and Vitamins
  "KEGG_RIBOFLAVIN_METABOLISM",
  "KEGG_NICOTINATE_AND_NICOTINAMIDE_METABOLISM",
  "KEGG_PANTOTHENATE_AND_COA_BIOSYNTHESIS",
  "KEGG_FOLATE_BIOSYNTHESIS",
  "KEGG_RETINOL_METABOLISM",
  "KEGG_PORPHYRIN_AND_CHLOROPHYLL_METABOLISM")
kegg.metab_xeno = c( 
  # Xenobiotics biodegradation and metabolism
  "KEGG_DRUG_METABOLISM_CYTOCHROME_P450",
  "KEGG_METABOLISM_OF_XENOBIOTICS_BY_CYTOCHROME_P450",
  "KEGG_DRUG_METABOLISM_OTHER_ENZYMES"
)
kegg.cp_transport_catabolism = c(
  "KEGG_ENDOCYTOSIS",
  "KEGG_LYSOSOME",
  "KEGG_PEROXISOME"
)

group = list()
group$kegg.metab_energy = kegg.metab_energy
group$kegg.metab_carbohydrate = kegg.metab_carbohydrate
group$kegg.metab_lipid = kegg.metab_lipid
group$kegg.metab_glycan = kegg.metab_glycan
group$kegg.metab_xeno = kegg.metab_xeno
group$kegg.metab_nucleotide = kegg.metab_nucleotide
group$kegg.metab_aminoacid = kegg.metab_aminoacid
group$kegg.cp_transport_catabolism = kegg.cp_transport_catabolism
group$kegg.kegg.metab_cofactor = kegg.metab_cofactor

